server:
  port: 8083
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/ratings/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotels/**,/api/staffs
  config:
   import: optional:configserver:http://localhost:8088 