server:
  port: 8090
spring:
  datasource:
    name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/practice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/