server:
  port: 8084
spring:
   application:
     name: USER-SERVICE
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1234
   jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
   config:
    import: optional:configserver:http://localhost:8088 
#profiles:
#active: prod 
#acutator configuration
management:
    health:
      circuitbreakers:
       enabled: true
    endpoints:
          web:
           exposure:
             include: health
    endpoint:
       health:
        show-details: always

#reslience configuration
resilience4j:
 circuitbreaker:
    instances:
      ratingHotelBreaker:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 6s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED